# Generated by Django 5.2.1 on 2025-05-20 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("original_title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("poster_path", models.CharField(blank=True, max_length=255, null=True)),
                ("backdrop_path", models.CharField(blank=True, max_length=255, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.PositiveIntegerField(blank=True, null=True)),
                ("popularity", models.FloatField(default=0)),
                ("origin_country", models.CharField(blank=True, max_length=10)),
                ("production_company", models.CharField(blank=True, max_length=100)),
                ("genres", models.ManyToManyField(related_name="movies", to="movie.genre")),
            ],
            options={
                "db_table": "movie",
            },
        ),
        migrations.CreateModel(
            name="MovieCast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("character", models.CharField(blank=True, max_length=100)),
                ("profile_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casts",
                        to="movie.movie",
                    ),
                ),
            ],
            options={
                "db_table": "cast",
            },
        ),
        migrations.CreateModel(
            name="MovieCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("profile_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crews",
                        to="movie.movie",
                    ),
                ),
            ],
            options={
                "db_table": "crew",
            },
        ),
    ]
